# Generated by Django 2.1.4 on 2018-12-24 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw', models.PositiveSmallIntegerField()),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_1_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_1_2', models.PositiveSmallIntegerField(null=True)),
                ('score_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_2_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_2_2', models.PositiveSmallIntegerField(null=True)),
                ('score_2', models.PositiveSmallIntegerField(null=True)),
                ('throw_3_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_3_2', models.PositiveSmallIntegerField(null=True)),
                ('score_3', models.PositiveSmallIntegerField(null=True)),
                ('throw_4_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_4_2', models.PositiveSmallIntegerField(null=True)),
                ('score_4', models.PositiveSmallIntegerField(null=True)),
                ('throw_5_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_5_2', models.PositiveSmallIntegerField(null=True)),
                ('score_5', models.PositiveSmallIntegerField(null=True)),
                ('throw_6_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_6_2', models.PositiveSmallIntegerField(null=True)),
                ('score_6', models.PositiveSmallIntegerField(null=True)),
                ('throw_7_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_7_2', models.PositiveSmallIntegerField(null=True)),
                ('score_7', models.PositiveSmallIntegerField(null=True)),
                ('throw_8_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_8_2', models.PositiveSmallIntegerField(null=True)),
                ('score_8', models.PositiveSmallIntegerField(null=True)),
                ('throw_9_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_9_2', models.PositiveSmallIntegerField(null=True)),
                ('score_9', models.PositiveSmallIntegerField(null=True)),
                ('throw_10_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_10_2', models.PositiveSmallIntegerField(null=True)),
                ('throw_fill', models.PositiveSmallIntegerField(null=True)),
                ('score_10', models.PositiveSmallIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game')),
            ],
        ),
    ]
