# Generated by Django 2.1.4 on 2018-12-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_auto_20181224_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(null=True)),
                ('throw_1', models.PositiveSmallIntegerField(null=True)),
                ('throw_2', models.PositiveSmallIntegerField(null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_filler', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='throw',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.Game'),
        ),
        migrations.AddField(
            model_name='round',
            name='score_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowling.ScoreSheet'),
        ),
    ]
