# Generated by Django 2.1.4 on 2018-12-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_auto_20181224_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='bowling.ScoreSheet'),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='bowling.Game'),
        ),
    ]
